-- =============================================================================
-- SNF Substrate DDL — generated by SNF Model Builder
-- lens_id:            discogs_v1
-- translator_version: 1.0.0
-- schema:             discogs
--
-- Run this first, then run load.sh (or the COPY commands manually).
-- =============================================================================

-- Create schema if needed (comment out if schema already exists)
-- CREATE SCHEMA IF NOT EXISTS "discogs";

-- Spoke tables (one per dimension)

CREATE TABLE IF NOT EXISTS "discogs"."snf_who" (
    entity_id          TEXT        NOT NULL,
    dimension          TEXT        NOT NULL,
    semantic_key       TEXT        NOT NULL,
    value              TEXT        NOT NULL,
    coordinate         TEXT        NOT NULL,
    lens_id            TEXT        NOT NULL,
    translator_version TEXT        NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_who_coordinate"
    ON "discogs"."snf_who" (coordinate);
CREATE INDEX IF NOT EXISTS "idx_who_entity_id"
    ON "discogs"."snf_who" (entity_id);
CREATE INDEX IF NOT EXISTS "idx_who_dim_key_val"
    ON "discogs"."snf_who" (dimension, semantic_key, value);

CREATE TABLE IF NOT EXISTS "discogs"."snf_what" (
    entity_id          TEXT        NOT NULL,
    dimension          TEXT        NOT NULL,
    semantic_key       TEXT        NOT NULL,
    value              TEXT        NOT NULL,
    coordinate         TEXT        NOT NULL,
    lens_id            TEXT        NOT NULL,
    translator_version TEXT        NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_what_coordinate"
    ON "discogs"."snf_what" (coordinate);
CREATE INDEX IF NOT EXISTS "idx_what_entity_id"
    ON "discogs"."snf_what" (entity_id);
CREATE INDEX IF NOT EXISTS "idx_what_dim_key_val"
    ON "discogs"."snf_what" (dimension, semantic_key, value);

CREATE TABLE IF NOT EXISTS "discogs"."snf_when" (
    entity_id          TEXT        NOT NULL,
    dimension          TEXT        NOT NULL,
    semantic_key       TEXT        NOT NULL,
    value              TEXT        NOT NULL,
    coordinate         TEXT        NOT NULL,
    lens_id            TEXT        NOT NULL,
    translator_version TEXT        NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_when_coordinate"
    ON "discogs"."snf_when" (coordinate);
CREATE INDEX IF NOT EXISTS "idx_when_entity_id"
    ON "discogs"."snf_when" (entity_id);
CREATE INDEX IF NOT EXISTS "idx_when_dim_key_val"
    ON "discogs"."snf_when" (dimension, semantic_key, value);

CREATE TABLE IF NOT EXISTS "discogs"."snf_where" (
    entity_id          TEXT        NOT NULL,
    dimension          TEXT        NOT NULL,
    semantic_key       TEXT        NOT NULL,
    value              TEXT        NOT NULL,
    coordinate         TEXT        NOT NULL,
    lens_id            TEXT        NOT NULL,
    translator_version TEXT        NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_where_coordinate"
    ON "discogs"."snf_where" (coordinate);
CREATE INDEX IF NOT EXISTS "idx_where_entity_id"
    ON "discogs"."snf_where" (entity_id);
CREATE INDEX IF NOT EXISTS "idx_where_dim_key_val"
    ON "discogs"."snf_where" (dimension, semantic_key, value);

CREATE TABLE IF NOT EXISTS "discogs"."snf_why" (
    entity_id          TEXT        NOT NULL,
    dimension          TEXT        NOT NULL,
    semantic_key       TEXT        NOT NULL,
    value              TEXT        NOT NULL,
    coordinate         TEXT        NOT NULL,
    lens_id            TEXT        NOT NULL,
    translator_version TEXT        NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_why_coordinate"
    ON "discogs"."snf_why" (coordinate);
CREATE INDEX IF NOT EXISTS "idx_why_entity_id"
    ON "discogs"."snf_why" (entity_id);
CREATE INDEX IF NOT EXISTS "idx_why_dim_key_val"
    ON "discogs"."snf_why" (dimension, semantic_key, value);

CREATE TABLE IF NOT EXISTS "discogs"."snf_how" (
    entity_id          TEXT        NOT NULL,
    dimension          TEXT        NOT NULL,
    semantic_key       TEXT        NOT NULL,
    value              TEXT        NOT NULL,
    coordinate         TEXT        NOT NULL,
    lens_id            TEXT        NOT NULL,
    translator_version TEXT        NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_how_coordinate"
    ON "discogs"."snf_how" (coordinate);
CREATE INDEX IF NOT EXISTS "idx_how_entity_id"
    ON "discogs"."snf_how" (entity_id);
CREATE INDEX IF NOT EXISTS "idx_how_dim_key_val"
    ON "discogs"."snf_how" (dimension, semantic_key, value);

-- Hub table (display + provenance)
CREATE TABLE IF NOT EXISTS "discogs"."snf_hub" (
    entity_id          TEXT        PRIMARY KEY,
    nucleus            TEXT,
    label              TEXT,
    sublabel           TEXT,
    lens_id            TEXT        NOT NULL,
    translator_version TEXT        NOT NULL
);

-- Affordances materialized view
-- Required for interactive speed at scale (50K+ entities).
-- Refresh with: REFRESH MATERIALIZED VIEW "discogs"."snf_affordances";
CREATE MATERIALIZED VIEW IF NOT EXISTS "discogs"."snf_affordances" AS
SELECT
    dimension,
    semantic_key,
    value,
    coordinate,
    COUNT(DISTINCT entity_id) AS entity_count,
    COUNT(*)                  AS fact_count
FROM (
    SELECT entity_id, dimension, semantic_key, value, coordinate FROM "discogs"."snf_who"
    UNION ALL
    SELECT entity_id, dimension, semantic_key, value, coordinate FROM "discogs"."snf_what"
    UNION ALL
    SELECT entity_id, dimension, semantic_key, value, coordinate FROM "discogs"."snf_when"
    UNION ALL
    SELECT entity_id, dimension, semantic_key, value, coordinate FROM "discogs"."snf_where"
    UNION ALL
    SELECT entity_id, dimension, semantic_key, value, coordinate FROM "discogs"."snf_why"
    UNION ALL
    SELECT entity_id, dimension, semantic_key, value, coordinate FROM "discogs"."snf_how"
) all_spokes
GROUP BY dimension, semantic_key, value, coordinate
WITH DATA;

CREATE INDEX IF NOT EXISTS "idx_affordances_dim_key"
    ON "discogs"."snf_affordances" (dimension, semantic_key);
CREATE INDEX IF NOT EXISTS "idx_affordances_coordinate"
    ON "discogs"."snf_affordances" (coordinate);
